### ISSUE TITLE
Shared Secret

### ISSUE THREAD

**Issue by nichdiekuh** [DoctorMcKay/node-steam-totp#1]
Hi,

I'm trying to figure how to get over the escrow hurdle and found the link to this lib in this issue https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/issues/31 

Where does the shared secret come from? Does steam provide a shared secret per trade offer?

**Comment by s992** [comment]
The shared secret is used to generate the auth code to log in to your account. You receive it in the callback of `enableTwoFactor` from [node-steamuser](https://github.com/DoctorMcKay/node-steam-user).
