### ISSUE TITLE
How to setup steam totp?

### ISSUE THREAD

**Issue by sword134** [DoctorMcKay/node-steam-totp#10]
I have been mocking around in the steam totp for 7 days now trying to find out where to paste the identity_secret, shared_secret and the code it self. Please i need some help it would really make my christmas! I just need to know where to paste my information and thats that. I hope its not too much to ask for.

**Comment by DoctorMcKay** [comment]
Please read the readme. There is even a usage example. If you don't understand it, then I recommend you take some JavaScript courses online.

**Comment by sword134** [comment]
Only thing i need to know is where to paste the values!

**Comment by andrewda** [comment]
It's always beneficial to read the README. In fact, I can't think of one time when not reading the README is acceptable in any circumstances. You'll only be doing yourself good by reading it, and it answers your question.
