### ISSUE TITLE
Confirm Action

### ISSUE THREAD

**Issue by ghost** [DoctorMcKay/node-steam-totp#13]
So I saw the method i saw the method of getting the key for doing yhis, but what url should I request and in what format?

**Comment by andrewda** [comment]
It doesn't request a URL. It generates auth codes using the same formula that the mobile app uses (see [the code](https://github.com/DoctorMcKay/node-steam-totp/blob/master/index.js#L18-L44)).

**Comment by ghost** [comment]
I am not mtalking about the code. I am talking about the key used to list an confirm actions.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getconfirmationstime-key-callback
