### ISSUE TITLE
How you active 2fa?

### ISSUE THREAD

**Issue by emdy** [DoctorMcKay/node-steam-totp#16]
What is the url to make request, like active 2fa and get other stuff?

**Comment by ghost** [comment]
You active 2FA on Steam Mobile App in "Steam Guard" !

**Comment by emdy** [comment]
@P4rkeR man its github - iam not askring about how to active auth like kid! I want know API.

https://lab.xpaw.me/steam_api_documentation.html#ITwoFactorService

**Comment by DoctorMcKay** [comment]
You can enable it using either [node-steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity) or [node-steam-user](https://github.com/DoctorMcKay/node-steam-user), or perhaps something else.

**Comment by emdy** [comment]
@DoctorMcKey tell me personaly - how you know steam 2fa this fast and allready get done? Its fact that you cant know this like first person lol

**Comment by DoctorMcKay** [comment]
It wasn't terribly hard to reverse engineer.

**Comment by emdy** [comment]
https://api.steampowered.com/ITwoFactorService/AddAuthenticator/v1/
API tells me i need a key, but you dont include key. why?

**Comment by andrewda** [comment]
I believe that is the default message given by Steam. This API, however, uses an `access_token` instead. You can see how @DoctorMcKay retreives the `access_token` by seeing the [`getWebApiOauthToken()` method](https://github.com/DoctorMcKay/node-steamcommunity/blob/5624611421ef448a822119491d73a318e04e7654/components/webapi.js#L41-L66).

**Comment by emdy** [comment]
cmon ansver lol https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/issues/79

**Comment by andrewda** [comment]
@emdy : Post your questions in the Steam group (linked @ https://github.com/DoctorMcKay/node-steam-tradeoffer-manager#support). By asking unrelated questions, you are spamming people who watch this library or node-steam-tradeoffer-manager with notifications that they don't need to see. You'll have a much better chance at getting an answer from @DoctorMcKay if you post in the Steam group.
