### ISSUE TITLE
The AuthCode generated is not correct.

### ISSUE THREAD

**Issue by ghost** [DoctorMcKay/node-steam-totp#17]
Hello,

I have a problem with Steamtotp.
The code generated by SteamTotp.generateAuthCode() is not valid.
I try to put the timeOffset provided me by SteamTotp.getTimeOffset().
The code generated with generateAuthCode(shared_secret, timeOffset) is different that the code generated by generateAuthCode(shared_secret) at the same time ,but not work too.

I did a lot of tests, but none has been conclusive :
- shared_secret in clear/hex/base64.
- timeOffset / (-timeOffset) / Totp.time() / Totp.time((-)timeOffset) in generateAuthCode.
- Try to connect my bot with 2FA code provided by Mobile Apps : it works.

I provide you my little source :

``` javascript
var shared_secret = 'Shared_secret in clear';
var SteamTotp = require('steam-totp');
SteamTotp.getTimeOffset(function(success, val, ping){
    console.log(val);  // val is an object variable that contains TimeOffset
});

var two_factor_code: SteamTotp.generateAuthCode(shared_secret, -30) // -30 is TimeOffset.
```

Thank you !

**Comment by DoctorMcKay** [comment]
Make sure you're using the correct shared_secret for your account. Make sure it's the base64 `shared_secret` value.

**Comment by ghost** [comment]
Thank you for your help Doctor !
Please, tell me if i'm in the true.
The shared_secret  is formatted like this 'A00000'.
shared_secret for 'A00000' in base64 is 'QTAwMDAw'.

**Comment by DoctorMcKay** [comment]
The shared_secret should already be in base64 when you get it from a file or a call to activate it.

**Comment by ghost** [comment]
I try like this, no success... I'm sorry. I'm may be idiot !

``` javascript
var shared_secret = 'A00000';
var base64 = 'QTAwMDAw';
var SteamTotp = require('steam-totp');
SteamTotp.getTimeOffset(function(success, val, ping){
    console.log(val);
});

var logOnOptions = {
    account_name: 'name',
    password: 'pass',
    two_factor_code: SteamTotp.generateAuthCode(base64, -33)
};
```

**Comment by jwigley** [comment]
Code looks ok (although you could use `val` variable instead of hardcoding -33). So most likely the `shared_secret` is not correct.

Did you extract the `shared_secret` from the steam guard file on the mobile?
As @DoctorMcKay said, you should just be able to plug it straight in, no need to convert.

**Comment by andrewda** [comment]
I agree with @jwigley. If plugging the `shared_secret` in by itself isn't working, there's an issue. You should never need to convert it.
- Are you sure the `shared_secret` is the secret of _this_ bot's account?
- Is the offset correct (using `val` should eliminate this possibility)?

Also, what happens when you `console.log(SteamTotp.generateAuthCode(base64, -33))`? Does it output a valid Steam Guard code? Can you try using that code on Steam's website with your bot's login information?

**Comment by ghost** [comment]
@jwigley, thank you very much. The steam guardian file on the mobile is the key of the solution =)
The function SteamTotp.generateAuthCode() works without TimeOffset !

Thank you everybody !
