### ISSUE TITLE
How to get "shared_secret"

### ISSUE THREAD

**Issue by lucasmonstrox** [DoctorMcKay/node-steam-totp#18]
Doctor McKay, can U tell me how to generate my "shared_secret"? I dont know nothing about it. :/

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-user#enabletwofactorcallback or https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#enabletwofactorcallback or extract it from a device that already has an authenticator on it.
