### ISSUE TITLE
Issue- not a function

### ISSUE THREAD

**Issue by ghost** [DoctorMcKay/node-steam-totp#22]
I am getting this error: 
steamtotp.getdeviceid is not a function

Any idea why?

Thanks.

**Comment by erickskrauch** [comment]
JavaScript is case sensitive programming language. Please use correct method name.

**Comment by ghost** [comment]
TypeError: SteamTotp.getDeviceID is not a function.....

**Comment by ghost** [comment]
var SteamTotp = require('steam-totp');

**Comment by ghost** [comment]
Solved by myself

**Comment by JonathanDelconte** [comment]
may I ask how you solved it?

**Comment by JonathanDelconte** [comment]
@lockthepot if you're still there :P
