### ISSUE TITLE
getConfirmationKey() function algorithm 

### ISSUE THREAD

**Issue by CyanoFresh** [DoctorMcKay/node-steam-totp#23]
Hello. I want to port getConfirmationKey() function in php. I am not so good on nodejs/javascript so can you provide step-by-step algorithm in this function(or comment every line in this one) like you did getDeviceID()? Thanks.

**Comment by srabouin** [comment]
https://github.com/Top-Cat/EscrowTF

Haven't used this but hopefully it helps you, good luck

**Comment by CyanoFresh** [comment]
Thanks. There is needed method
