### ISSUE TITLE
getDeviceID(steamID)

### ISSUE THREAD

**Issue by hrvasiliy** [DoctorMcKay/node-steam-totp#25]
I get the same error:
[https://github.com/DoctorMcKay/node-steam-totp/issues/21](url)
where to insert this code? 

``` javascript
SteamTotp.getDeviceID(steamID);
```

Explain how to use getDeviceID... pls

**Comment by andrewda** [comment]
> where to insert this code?

What do you mean? What isn't working?

**Comment by hrvasiliy** [comment]
The documentation is written: 

> getDeviceID(steamID)
> v1.3.0 or later is required to use this function

where should I use it?

**Comment by DoctorMcKay** [comment]
Chances are, if you don't know where to use it, you don't need it. There are a few modules that handle trade confirmations, which is all that's useful for.

**Comment by hrvasiliy** [comment]
@DoctorMcKay 

> Returns a standardized device ID in the same format as Android device IDs from Valve's official mobile app. Steam will likely soon stop allowing you to send a different device ID each time you load the page, instead requiring you to consistently use the same device ID. If you use this function's algorithm everywhere you use a confirmation device ID, then your experience should be fine.

I don't want the valve I was blocked. So I want to understand where to use getDeviceID. Please show an example

**Comment by hrvasiliy** [comment]
@DoctorMcKay This is my code:

``` javascript
 var timeConf = getDate();
 var keyConf  = SteamTotp.getConfirmationKey(identitySecret, timeConf, 'conf');

  community.getConfirmations(timeConf, keyConf, function (err, confirmations) {
    if (err) throw err;
  });
}
```

and I get an error:

> return "android:" + Crypto.createHash('sha1').update(steamID.toString()).digest('hex')
> TypeError: Cannot read property 'toString' of undefined

**Comment by Cj1m** [comment]
@hrvasiliy Surely you can see what the error is for yourself: 'toString' of undefined, meaning you've got an undefined variable

**Comment by iliaxone** [comment]
@Cj1m What should I change in my code in order to properly use getDeviceID?

**Comment by hrvasiliy** [comment]
@Cj1m What should I change in my code in order to properly use getDeviceID?

**Comment by Cj1m** [comment]
@hrvasiliy Have you defined identitySecret?

**Comment by hrvasiliy** [comment]
@Cj1m Yes. I got it from my iPad.
If I use [login](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#logindetails-callback) everything works but I can't change bot status! If I use [logOn](https://github.com/DoctorMcKay/node-steam-user#logondetails) + [webSession](https://github.com/DoctorMcKay/node-steam-user#websession) nothing works.

**Comment by hrvasiliy** [comment]
My code: 
[bot.js does not work](https://gist.github.com/hrvasiliy/4b92058fa7853f963bf5)
[bot.js works fine](https://gist.github.com/hrvasiliy/920814628b30fb88c371)

**Comment by DoctorMcKay** [comment]
That error happens if you try to interact with confirmations without first being logged in.

**Comment by hrvasiliy** [comment]
@DoctorMcKay Please tell me do I need to change the script to use getDiveceID or everything is done automatically?

**Comment by DoctorMcKay** [comment]
If you're on the latest version of node-steamcommunity, it's already done.
