### ISSUE TITLE
What is `secret`?

### ISSUE THREAD

**Issue by Jefftopia** [DoctorMcKay/node-steam-totp#26]
Docs say: 

```
getAuthCode(secret[, timeOffset])

secret - Your shared_secret, as a Buffer, hex string, or base64 string
```

But what is `secret`?

**Comment by DoctorMcKay** [comment]
You get it after enabling 2FA: https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#enabletwofactorcallback
