### ISSUE TITLE
Fail to instal npm steam-totp

### ISSUE THREAD

**Issue by jowy88** [DoctorMcKay/node-steam-totp#30]
Hi, 

Could you help me please, It fail to instal steam-totp. 
here is my log file : https://gist.github.com/jowy88/063cc4dc22c37962ea3f6a407ee5f838

npm -v prints: 3.10.10
node -v prints: v6.11.1
npm config get registry prints: https://registry.npmjs.org

using windows 10

Thank you for your help.

**Comment by DoctorMcKay** [comment]
Are you installing it through package.json? Through the command line? If through package.json, please show that here.

**Comment by jowy88** [comment]
I am installing it through the command line. I don"t know how to do it through package.json,

**Comment by DoctorMcKay** [comment]
Please show the command you're using to install it.

**Comment by jowy88** [comment]
Hey, thanks for you answer it's now fixed. I had downloadan old version of your package, that's why it failed. I didn"t saw you did an update. Now the install worked fine wich the good files.

Sorry I'm really new about this and I'm following a tutorial, I just know very little basic C, php and javascript. But I'm still learning to improve.

Thank you Rodney Merefith Mckay for your answer and your work. Have a nice day/evening.
