### ISSUE TITLE
totp code does not match what steam mobile generates

### ISSUE THREAD

**Issue by zensonic** [DoctorMcKay/node-steam-totp#31]
Hi
I have downloaded your nice node-steam-totp module (both using npm and stand alone with git). I then wrote a simple three line use.js program like

```
mathias@edison:~/test/node-steam-totp$ cat use.js 
var steam = require('./index.js');
var totp = steam.generateAuthCode('HAHAHA_AS_IF=');
console.log("TOTP:", totp);

```
Where I took the identity secret from accounts.json from backpack.tf-automatic. And I can generate 5 digit codes. Both with the npm version and the git version. And they generate the same 5 digit code. Problem is that 1) they do not mach what I get in steam-mobile app (which works) and 2) the don't work when I use them. 

What am I doing wrong? I thought it was a time issue, but debugging the index.js file yields an offset of 0 wrt the time on the steam servers. 

Any hints really appricated.

**Comment by DoctorMcKay** [comment]
You should use `shared_secret` to get a login code, not `identity_secret`.

**Comment by zensonic** [comment]
Thanks. Facepalm. New to steam (helping Kid with some code). Works perfectly with shared_secret.
