### ISSUE TITLE
Cannot sign in on other device

### ISSUE THREAD

**Issue by michelgiehl** [DoctorMcKay/node-steam-totp#36]
Hello! If I Use my local computer, I can generate the 2 factor code using the shared_secret. But when I upload the script to a linux server, it cannot generate the 2 factor code. please help.

**Comment by DoctorMcKay** [comment]
Either your clock is wrong or your secret is wrong.

**Comment by Billason** [comment]
Hello DoctorMckay
I tried to use
twoFactorCode: SteamTotp.generateAuthCode(config.shared_secret)
but still not working how can I fix this?

**Comment by DoctorMcKay** [comment]
Either your clock is wrong or your secret is wrong.

**Comment by Billason** [comment]
how could that happen???
