### ISSUE TITLE
Update Example In Readme.md

### ISSUE THREAD

**Issue by srexi** [DoctorMcKay/node-steam-totp#38]
Didn't want to make  a fork for it since it's nothing but maybe update the example

var SteamTotp = require('steam-totp');
var code = SteamTotp.generateAuthCode('cnOgv/KdpLoP6Nbh0GMkXkPXALQ=');

To:

var SteamTotp = require('steam-totp');
var code = SteamTotp.getAuthCode('cnOgv/KdpLoP6Nbh0GMkXkPXALQ=');

In https://github.com/DoctorMcKay/node-steam-totp/blob/master/README.md

**Comment by andrewda** [comment]
But... why?

**Comment by titoncio** [comment]
These two methods works fine, since ___generateAuthCode___ is an alias for ___getAuthCode___

**Comment by srexi** [comment]
oh wow I missed that.. thanks @titoncio  for pointing that out
