### ISSUE TITLE
Shared Secret

### ISSUE THREAD

**Issue by yaneony** [DoctorMcKay/node-steam-totp#4]
Sorry for such a duplicate, but it's not that clear. Yeah, a was looking around and googling, but notinh found.

As it was said early here https://github.com/DoctorMcKay/node-steam-totp/issues/1 you can retrieve shared_secret with enableTwoFactor method.

Hope that part of code is right:

``` javascript
var SteamUser = require('steam-user');
var client = new SteamUser();
client.logOn({
  "accountName": 'USER',
  "password": 'PASS'
});

client.on('loggedOn', function(){
  console.log('Logged In');
  client.enableTwoFactor(function(secret, activationCode) {
    console.log(secret);
    console.log(activationCode);
  });
});
```

As result there only

{ status: 29 }
undefined

What i'm doing wrong?

**Comment by yaneony** [comment]
Sorry, forgot to remove my credentials.

**Comment by DoctorMcKay** [comment]
29 = DuplicateRequest

You already have 2FA enabled.

**Comment by yaneony** [comment]
Okay, so if it's already enabled, is there still a way to retrieve the shared_secret?

**Comment by DoctorMcKay** [comment]
Not without rooting/jailbreaking your phone.

**Comment by yaneony** [comment]
So, that means the only way is to disable and then enable the 2FA again, right?

**Comment by DoctorMcKay** [comment]
Yes.
