### ISSUE TITLE
generateConfirmationKey ERR_OUT_OF_RANGE

### ISSUE THREAD

**Issue by Tehpson** [DoctorMcKay/node-steam-totp#41]
I get:

  node:internal/buffer:70
      throw new ERR_OUT_OF_RANGE('value', range, value);
      ^
  
  RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 1_615_059_598_889

When calling for generateConfirmationKey:

  var time = Date.now();
    var confKey = SteamTotp.generateConfirmationKey(config.identitySecret,time,'conf');
    var allowKey = SteamTotp.generateConfirmationKey(config.identitySecret,time,'allow');

**Comment by jmopel** [comment]
Try this:
```js
const time = SteamTotp.time()
const confKey = SteamTotp.getConfirmationKey(config.identitySecret, time, 'conf')
const allowKey = SteamTotp.getConfirmationKey(config.identitySecret, time, 'allow')
```

**Comment by Tehpson** [comment]
Thanks @Jmopel It worked
