### ISSUE TITLE
Generate wrong TOTP code

### ISSUE THREAD

**Issue by zhuang42** [DoctorMcKay/node-steam-totp#42]
I use `shared_secret` to generate TOTP code for my bot but it's not the same as on the SDA

Code is pretty limited, 
```
var SteamTotp = require('steam-totp');
var code = SteamTotp.generateAuthCode('***secret***');
```

Do you have any idea?

**Comment by jmopel** [comment]
Make sure you actually use correct `shared_secret` (with `=` at the end), not `secret` from SDA. Also make sure that the time on the devices is synchronized with the world time.

**Comment by zhuang42** [comment]
> Make sure you actually use correct `shared_secret` (with `=` at the end), not `secret` from SDA. Also make sure that the time on the devices is synchronized with the world time.

Thanks for replying! I just found out my friend gave me a wrong `shared_secret` of another bot. Gonna close this issue
