### ISSUE TITLE
Is identity_secret DeviceID

### ISSUE THREAD

**Issue by gosthell** [DoctorMcKay/node-steam-totp#5]
I hate to be this type of guy, but I have my account configured with winauth, and in my winauth config file, I don't have identity_secret but DeviceID which is a 96 char string (encoded by C# function BitConverter.ToString()). Could this be the identity_secret that has to be passed to getConfirmationKey() ? Because it doesn't seems to work. If it is not, is there a way to retrieve the identity_secret without revoking and enabling twoFacor again ? Thanks a lot, and thanks for these librairies.

**Comment by srabouin** [comment]
It's not, and you can't get it from winauth -- winauth only saves the shared secret since that's all they need to generate the key.

**Comment by gosthell** [comment]
Okay thanks :)
