### ISSUE TITLE
Can you make in php ?

### ISSUE THREAD

**Issue by pyaehein** [DoctorMcKay/node-steam-totp#7]
Can you do registering twofactor device and generating login code function for php? 
Because i don't have nodejs and i don't know about nodejs. 
Please, I really need to use it. Thank you.

I means these 3 function from your codes

SteamCommunity.prototype.enableTwoFactor = function(callback),
SteamCommunity.prototype.finalizeTwoFactor = function(secret, activationCode, callback)
and
exports.generateAuthCode = exports.getAuthCode = function(secret, timeOffset)

ps: if you are too busy, generateAuthCode function may be ok for me. (i will get secret key from phone)

**Comment by DoctorMcKay** [comment]
I'm sure it _can_ be done, but I don't have time or interest in doing so.

**Comment by srabouin** [comment]
https://github.com/Top-Cat/EscrowTF enjoy

**Comment by pyaehein** [comment]
Yay! Thank you @srabouin
