### ISSUE TITLE
timeOffset (question)

### ISSUE THREAD

**Issue by zickyp** [DoctorMcKay/node-steam-totp#9]
Question, how can i tell if my local machine is timeOffset value is right with steams servers.  I am able to generate the code but it doesnt seem right when i check with my application  in real time.

**Comment by Lagg** [comment]
Refer to `ITwoFactorService/QueryTime/v1`

Chances are though, if this is actually causing you problems there's something deeper than time diffs. Because your machine will have more problems to worry about if there's a persistent 5 minute+ drift

**Comment by zickyp** [comment]
Lagg, sorry for being such a noob but where can i find that  refrence?

**Comment by andrewda** [comment]
https://lab.xpaw.me/steam_api_documentation.html#ITwoFactorService_QueryTime_v1

It returns something like this:

```
{
  "response": {
    "server_time": "1450631490",
    "skew_tolerance_seconds": "60",
    "large_time_jink": "86400",
    "probe_frequency_seconds": 3600,
    "adjusted_time_probe_frequency_seconds": 300,
    "hint_probe_frequency_seconds": 60,
    "sync_timeout": 60,
    "try_again_seconds": 900,
    "max_attempts": 3
  }
}
```

**Comment by zickyp** [comment]
Well i executed the code from  miami, and im working on it from  south africa,and my code executed but its not syning up.

**Comment by zickyp** [comment]
Which property is the time difference, or how do you work it out

**Comment by DoctorMcKay** [comment]
Subtract Steam's time from your own local time.

**Comment by zickyp** [comment]
Hello gentelmen, how do i  verify  if my clocks working correctly, everything i try  doesnt work and I've tried  all the time zones and  variation within my current time frame  up to -+60.And no luck. :(

**Comment by andrewda** [comment]
Did you read above? You can see how accurate your clock is compared to Steam's by making a POST request to `ITwoFactorService/QueryTime/v1` (documentation: https://lab.xpaw.me/steam_api_documentation.html#ITwoFactorService_QueryTime_v1) and subtracting `server_time` from your local computer's time.

**Comment by zickyp** [comment]
Guys,  so found out what the problem was,  the way i was extracting the shared_secret was messed up, i was using the rooted phone method and after using the authenticator desktop method, i was able to retrieve the proper information from the json files.  I thank everyone for there support and test of patience on your parts.  Thank you again , it couldnt of been made possible without your continued support.
